services:
  - type: web
    name: todo-list
    env: java
    buildCommand: "./mvnw clean package"
    startCommand: "java -jar target/todolist-1.0.0.jar"
    plan: free
    envVars:
      - key: JAVA_VERSION
        value: 17
